### ISSUE TITLE
pinta called with --no-rficlean option, but it produces fits and ps files with .gptool extension 

### ISSUE THREAD

**Issue by tprabu2000** [abhisrkckl/pinta#14]
pinta when called with --no-rficlean option the fits and ps outputs appear with .gptool extension.

command used:   pinta  --log-to-file --retain-aux --no-rficlean ../. ./.

**Comment by abhisrkckl** [comment]
This is the expected behaviour.

The expected behaviour of --no-xxxx flags are as follows:

**pinta --no-gptool** --> norfix & rficlean
**pinta --no-rficlean** --> gptool
**pinta --no-gptool --no-rficlean** --> norfix
**pinta** --> gptool & rficlean

**Comment by tprabu2000** [comment]
Thanks for the clarification.
