### ISSUE TITLE
Pipeline moves/removes files that are not generated by pinta

### ISSUE THREAD

**Issue by ymaan4** [abhisrkckl/pinta#15]
The --retain-aux option seems to filter and move files on the basis of extension. This results in moving the files that are actually not created by pinta, which is not desirable. I have noticed this happening with *.info files, might also be true for other types. Extrapolating from this, the absence of --retain-aux will imply that pinta could potentially delete files that are not its intermediate products but rather created by someone else, which could be very damaging.

**Comment by abhisrkckl** [comment]
This was done to clean up the large number of auxiliary output files which are created during the process. 
I will fine-tune this to ensure that only files created by pinta or its subprocesses are (re)moved.

**Comment by abhisrkckl** [comment]
Fixed in Commit bfb0d6b3efcd114ff6ab0c1c99aa297643081b81

**Comment by abhisrkckl** [comment]
Tested and it works.
