### ISSUE TITLE
Option to fold data to an Nbin value in addition to the one provided in the pipeline.in file

### ISSUE THREAD

**Issue by abhisrkckl** [abhisrkckl/pinta#21]

**Comment by ymaan4** [comment]
The issue-title should rather read "Option to create profiles with two choices of number of bins", as the pipeline doesn't really decide or check of the number of bins are Nyquist sampled or oversampled.

**Comment by ymaan4** [comment]
An efficient way of doing that would be to add a provision to read an extra number (integer) from an additional (last, non-mandatory) column in the pipeline.in file. If the column/number is not provided then nothing extra happens, if it is provided then an extra set of archive/psrfits files are produced with number of bins equal to the specified number times the earlier specified bins.

**Comment by abhisrkckl** [comment]
We discussed this at length yesterday and decided that it is better not to break the format of the pipeline.in file. 

The pipeline.in file already contains all the information needed to compute the Nyquist number of bins. So we decided to have a "--nyquist" option which will fold the data to Nyquist number of bins in addition to whatever nbin is there in the pipeline.in file.

**Comment by abhisrkckl** [comment]
Implemented in commit 7fd9a4194499814fc43d7a0f8476e1cd30a6c8bc

**Comment by abhisrkckl** [comment]
I am implementing this feature as follows:

- pinta will compute the "default" NBin value if NBin=-1 is given in the pipeline.in file. This value corresponds to 2**(floor(log2(P0/Tsmpl)).
- dspsr can be run again with a different binning using the --xnbin <x> option. The new number of bins value will be x*NBin.

**Comment by abhisrkckl** [comment]
Tested and it works.
