### ISSUE TITLE
pinta --test option fails

### ISSUE THREAD

**Issue by pratikta16** [abhisrkckl/pinta#28]
After gptool > ugmrt2fil > dspsr, error thrown while interpreting the following function in pintaexec.py (line 146) -

def run_dspsr(session, item, branch, xnbin=False):
    program = 'dspsr'
    exec_cmd(session, item, branch, program, xnbin=xnbin)

    # Checking if output file is created
    if not xnbin:
        fits_file = "./" + output_file_name(session, item, branch, 'fits')
    else:
        fits_file = "./" + output_file_name(session, item, branch, '{}xNBin.fits'.format(session.xnbinfac))

    if not os.access(fits_file, os.F_OK):
        print("[ERROR] dspsr failed to create file {} ... Quitting...".format(fits_file))
        raise OSError

Crosschecks - Tried running pinta with (a) --no-gptool, (b) --no-rficlean and (c) the full version. Works fine. Summary files generated as expected. So, probably no path issues. Only fails when pinta is invoked with the --test option.

Observations - It may have something to do with the naming conventions. gptool output is renamed as per ugmrt2fil convention as (say) -
mv ./J2124-3358.09Mar2020.band3cdp.dat.gpt ./J2124-3358_58917.211001_500.gptool.gpt.dat
The renaming command doesn’t get displayed on screen following gptool execution during --test run.

**Comment by abhisrkckl** [comment]
The check `if not os.access(fits_file, os.F_OK)` should not have been performed while running in `--test` mode. I will fix this once this round of testing is over.

**Comment by pratikta16** [comment]
Ok. Got it.
