### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by abhisrkckl** [abhisrkckl/pinta#8]
Add a README for installation.

**Comment by ymaan4** [comment]
In README file, there is the following line:
`cp pinta/pinta pinta/pinta*.py pinta/pinta.yaml pinta/crp_rficlean_gm.sh /pinta/install/path/`

I think `pinta/crp_rficlean_gm.sh` here is leftover from the previous version as there is no `crp_rficlean_gm.sh` in `pinta`?

**Comment by ymaan4** [comment]
I vaguely remember mentioning maintenance issues if we keep `crp_rficlean_gm.sh` in `pinta`, perhaps that's when this script was moved out of `pinta`.

**Comment by abhisrkckl** [comment]
Removed the reference to `crp_rficlean_gm.sh`.
